services:
  db:
    image: postgres:16-alpine
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    restart: always
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - db
      - frontend
      - backend
    restart: always
  frontend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./prof_frontend:/app
      - /app/node_modules # anonymous volume to prevent host override
    # -- (The End-of-Options Delimiter): This tells npm to stop parsing arguments for itself. Anything passed after the double dash is forwarded directly to the underlying tool, which in this case is Vite.
    # --host: This is the argument received by Vite. It forces Vite to expose the local server instead of keeping it restricted to your machine. 
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - VITE_API_URL=/api # relative, since nginx proxies it
  backend:
    image: cosmtrek/air # air is available as an image
    working_dir: /app
    volumes:
      - ./hobby_backend:/app
      - go-mod-cache:/go/pkg/mod # cache modules between restarts
      - go-build-cache:/.cache/go-build
    env_file:
      - ".env"
    command: sh -c "go mod download && air"

volumes:
  go-mod-cache:
  go-build-cache:
